---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# influenceR

<!-- badges: start -->
<!-- badges: end -->

The goal of influenceR is to ...

## Installation

You can install the development version of influenceR from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("adamglux/A2DATA501")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(influenceR)
## basic example code

#import dataset mtcars
data1 <- mtcars
model1 <- lm(mpg ~ wt + hp, data = data1)

## run function to create influence measures + plots
sample1 <- influenceR(model1, data1, "all")

## run function to create dataframe only (no plots)
sample2 <- influenceR(model1, data1)

## show dataframe of measures
#sample1$influence_measures

## view / manipulate individual influence measure
#sample2$DFFITs

```

```{r echo=F, fig.height=4, fig.width=6}
## show plots

## show individual plots
sample1$plots$Cooks + theme_minimal()
sample1$plots$DFFITS + theme_minimal()
sample1$plots$Hadi + theme_minimal()



```




You can also embed plots, for example:

```{r pressure, echo = FALSE}
plot(pressure)
```

In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN.
